name: PizzaKartRacers
version: '${project.version}'
main: me.pizzathatcodes.pizzakartracers.Main
api-version: '1.20'
author: PizzaThatCodes
description: A plugin that adds PizzaKartRacers to Minecraft.
depend:
  - ProtocolLib
commands:
  getkart:
    description: Get a kart.
    usage: /getkart <kart>
